name:02 - Workflow Events
on:
  push:
  pull_request:
  schedule:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      name: Show the trigges
      run: echo "This will print the type of event that triggered the workflow"
      
