name: 04 -  Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app


    #0. check the code from the repo
    # 1. Install deps of our react app
    #2. Run automated tests